### ISSUE TITLE
Регістрозалежність

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [kateryna-nikolaienko/kateryna-nikolaienko.github.io#27]
Деякі OS, такі як windwos регістронезалежні - що означає що їм без різниці в якомі зегістрі записана назва файлу/папки. Для таких `context` та `Сontext` це одне і теж. Але більшість серверів працюють з Linux - а для нього це різні файли (в MacOS також). Тому може траплятись таке
<img width="1531" alt="Знімок екрана 2023-05-01 о 19 23 59" src="https://user-images.githubusercontent.com/59687966/235496442-0aa4174d-87c4-4071-8163-2003db7b4c1d.png">
Виправити можна просто переіменувавши папку `Context` на `context`

**Comment by kateryna-nikolaienko** [comment]
Хмм.. дивно.. В локальному середовищі в мене в маленькому регістрі
